
name: 'Godot Engine: Export to iOS and upload to Testflight'

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  godot-version:
    description: 'Godot Engine version'
    required: false
    default: '3.5'
  project-name:
    description: 'Project name used for xarchive building'
    required: true
  apple-id-username:
    description: 'Apple ID username'
    required: true
  apple-id-password:
    description: 'Apple ID password'
    required: true
  provisioning-profile-id:
      description: 'Provisioning profile ID'
      required: true
  cache-version:
    description: 'Version for Godot files cache, to be able to clear cache'
    required: false
    default: 1

  
runs:
  using: "composite"
  steps:
    - name: Check is running on mac-os
      if: runner.os != 'macos'
      shell:
      run: exit 1
    
    - name: Cache Godot files
      id: cache-godot
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/godot/**
          ~godot
          ~/.config/godot/**
        key: ${{ runner.os }}-godot-${{ inputs.godot-version }}-v${{ inputs.cache-version }}

    - name: Download and config Godot Engine headless linux server and templates
      if: steps.cache-godot.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget -q https://github.com/huskeee/godot-headless-mac/releases/download/${{ inputs.godot-version }}-stable/Godot_v${{ inputs.godot-version }}-stable_mac_headless.64.zip
        wget -q https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        unzip Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz
        unzip Godot_v${{ inputs.godot-version }}-stable_mac_headless.64.zip
        mkdir -p ~/.config/godot
        mkdir -p ~/.local/share/godot/templates/${{ inputs.godot-version }}.stable
        mv templates/* ~/.local/share/godot/templates/${{ inputs.godot-version }}.stable
        mv bin/godot .
        ./godot -e -q

        rm -f Godot_v${{ inputs.godot-version }}-stable_linux_headless.64.zip Godot_v${{ inputs.godot-version }}-stable_export_templates.tpz

    - name: Godot iOS export
      shell: bash
      run: ./godot --path ${{ inputs.working-directory }} --export iOS

    - name: Force XCode 12.5.1
      shell: bash
      run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app

    - name: Resolve package dependencies
      shell: bash
      run: xcodebuild -resolvePackageDependencies

    - name: Build the xarchive
      shell: bash
      run: |
        set -eo pipefail
        xcodebuild  clean archive \
          -scheme ${{ inputs.project-name }} \
          -configuration "Release" \
          -sdk iphoneos \
          -archivePath $PWD/build/${{ inputs.project-name }} \
          -destination "generic/platform=iOS,name=Any iOS Device" \
          OTHER_CODE_SIGN_FLAGS="--keychain $RUNNER_TEMP/app-signing.keychain-db" \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE=${{ inputs.provisioning-profile-id }} \
          CODE_SIGN_IDENTITY="Apple Distribution"

    - name: Export .ipa
      shell: bash
      run: |
        set -eo pipefail
        xcodebuild -archivePath "$PWD/build/${{ inputs.project-name }}" \
          -exportOptionsPlist exportOptions.plist \
          -exportPath $PWD/build \
          -allowProvisioningUpdates \
          -exportArchive

    - name: Publish the App on TestFlight
      shell: bash
      if: success()
      env:
        APPLEID_USERNAME: ${{ inputs.apple-id-username }}
        APPLEID_PASSWORD: ${{ inputs.apple-id-password }}
      run: |
        xcrun altool \
          --upload-app \
          -t ios \
          -f $PWD/build/{{ inputs.project-name }}.ipa \
          -u "${{ inputs.apple-id-username }}" \
          -p "${{ inputs.apple-id-password }}" \
          --verbose